// ============================================================
//  src/firebase/cardsService.ts
//  Source of truth for "Action Vérité Tounsiya" game cards.
//  Reads and writes directly to Firestore `cards/{cardId}`.
//  Provides full backward compatibility with legacy schema (cardType,
//  questionOrAction, etc.) while guaranteeing real-time updates for
//  Admin CMS creations, modifications, deactivations, and deletions.
// ============================================================

import { db } from './config';
import {
  collection,
  onSnapshot,
  getDocs,
  doc,
  setDoc,
  deleteDoc,
} from 'firebase/firestore';
import { GameCard, CardCategory, CardDifficulty } from '../types';

type LegacyLang = 'en' | 'fr' | 'tn';
type LegacyI18n = Partial<Record<LegacyLang, string>> | string | undefined;

function getLangPriority(lang?: string): LegacyLang[] {
  if (lang === 'fr') return ['fr', 'tn', 'en'];
  if (lang === 'en') return ['en', 'fr', 'tn'];
  return ['tn', 'fr', 'en'];
}

/** Old docs may store text as a plain string OR an {en,fr,tn} object — handle both safely. */
function pickI18n(value: LegacyI18n, preferred?: LegacyLang[]): string {
  if (!value) return '';
  if (typeof value === 'string') return value;
  const langs = preferred || ['tn', 'fr', 'en'];
  if (typeof value === 'object') {
    for (const lang of langs) {
      if ((value as any)[lang] && typeof (value as any)[lang] === 'string') return (value as any)[lang] as string;
    }
    if ((value as any).ar && typeof (value as any).ar === 'string') return (value as any).ar;
    for (const k of Object.keys(value)) {
      if ((value as any)[k] && typeof (value as any)[k] === 'string') return (value as any)[k];
    }
  }
  return '';
}

interface ParsedOptions {
  optionA?: string;
  optionB?: string;
}

/** 'normal'/'gold' cards store their two choices as a JSON blob in `description` (admin.js convention). */
function parseOptionsBlob(description: unknown): ParsedOptions {
  if (typeof description !== 'string' || !description.trim().startsWith('{')) return {};
  try {
    const parsed = JSON.parse(description);
    const options = Array.isArray(parsed?.options) ? parsed.options : [];
    return {
      optionA: options[0]?.text || undefined,
      optionB: options[1]?.text || undefined,
    };
  } catch {
    return {};
  }
}

function categoryForLegacyCard(cardType: string, tags: string[]): CardCategory {
  switch (cardType) {
    case 'green':
      return 'shield';
    case 'gold':
      return 'special';
    case 'red':
      return tags.includes('askQuestion') ? 'truth' : 'action';
    case 'normal':
    default:
      return 'truth';
  }
}

/** Turns a raw `cards/{id}` doc into RAKCHA GAME's GameCard shape. Never throws. */
export function normalizeLegacyCard(id: string, raw: Record<string, unknown>, userLang?: string): GameCard {
  const langPriority = getLangPriority(userLang);
  const cardType = typeof raw.cardType === 'string' ? raw.cardType : (typeof raw.type === 'string' ? raw.type : 'normal');
  const tags = Array.isArray(raw.tags) ? (raw.tags as string[]) : [];
  
  // If explicitly stored as category (e.g. created/updated from Admin CMS), respect it first.
  const category: CardCategory = (raw.category && ['action', 'truth', 'shield', 'special'].includes(raw.category as string))
    ? (raw.category as CardCategory)
    : categoryForLegacyCard(cardType, tags);

  // Check content: prioritize explicit string content, fallback to i18n question/action/text/prompt/question
  const explicitContent = typeof raw.content === 'string' && raw.content.trim()
    ? raw.content.trim()
    : (typeof raw.prompt === 'string' && raw.prompt.trim() ? raw.prompt.trim() : (typeof raw.question === 'string' && raw.question.trim() ? raw.question.trim() : ''));
  const questionText = pickI18n((raw.questionOrAction as LegacyI18n) ?? (raw.text as LegacyI18n) ?? (raw.question as LegacyI18n) ?? (raw.prompt as LegacyI18n), langPriority);
  let content = explicitContent || questionText || (typeof raw.content === 'string' ? raw.content : '');

  const { optionA, optionB } = parseOptionsBlob(raw.description);

  const plainDescription = typeof raw.description === 'string' && !raw.description.trim().startsWith('{')
    ? raw.description
    : pickI18n(raw.rule as LegacyI18n, langPriority);

  const penaltyText = pickI18n(raw.penalty as LegacyI18n, langPriority);

  const rawName = typeof raw.name === 'string' ? raw.name : '';
  const looksAutoGenerated = /^[a-z0-9_-]+-(normal|red|green|gold)-[a-z0-9]{1,6}$/i.test(rawName);
  const title = (typeof raw.title === 'string' && raw.title)
    ? raw.title
    : (rawName && !looksAutoGenerated
        ? rawName
        : (pickI18n(raw.title as LegacyI18n, langPriority) || category.toUpperCase()));

  let specialOptions: GameCard['specialOptions'] = undefined;

  if (raw.specialOptions && typeof raw.specialOptions === 'object') {
    const opts = raw.specialOptions as any;
    if (opts.optionA && opts.optionB) {
      specialOptions = { optionA: String(opts.optionA), optionB: String(opts.optionB) };
    }
  }

  if (category === 'special' && !specialOptions) {
    specialOptions = optionA && optionB ? { optionA, optionB } : undefined;
    content = content || [optionA, optionB].filter(Boolean).join(' / ');
  } else if (category === 'shield' && !content) {
    content = plainDescription || questionText || 'Protection card.';
  }

  const isActive = raw.isActive !== undefined
    ? raw.isActive !== false
    : (raw.enabled !== undefined ? raw.enabled !== false : raw.active !== false);

  const mode = typeof raw.mode === 'string' ? raw.mode : 'friends';
  const difficulty = (typeof raw.difficulty === 'string' ? raw.difficulty : 'medium') as CardDifficulty;
  const order = typeof raw.order === 'number' ? raw.order : 0;

  return {
    id,
    category,
    title: title || 'Action Vérité',
    content: content || '...',
    mode,
    difficulty,
    order,
    description: category === 'shield' ? (pickI18n(raw.rule as LegacyI18n) || plainDescription || undefined) : (penaltyText || plainDescription || undefined),
    imageUrl: typeof raw.imageUrl === 'string' && raw.imageUrl.trim() ? raw.imageUrl.trim() : undefined,
    specialOptions,
    isActive,
    createdAt: typeof raw.createdAt === 'string' ? raw.createdAt : undefined,
    updatedAt: typeof raw.updatedAt === 'string' ? raw.updatedAt : undefined,
    createdBy: typeof raw.createdBy === 'string' ? raw.createdBy : undefined,
    updatedBy: typeof raw.updatedBy === 'string' ? raw.updatedBy : undefined,
  };
}

/** One-time fetch — used to seed AppContext on load. */
export async function fetchActionVeriteCards(): Promise<GameCard[]> {
  try {
    const cardsRef = collection(db, 'cards');
    const snap = await getDocs(cardsRef);
    return snap.docs.map((d) => normalizeLegacyCard(d.id, d.data()));
  } catch (err: any) {
    // eslint-disable-next-line no-console
    console.warn('[rakcha] fetchActionVeriteCards fallback:', err?.message || err);
    return [];
  }
}

/** Real-time listener so changes made in Admin CMS reflect instantly everywhere. */
export function listenToActionVeriteCards(callback: (cards: GameCard[]) => void) {
  const cardsRef = collection(db, 'cards');
  return onSnapshot(
    cardsRef,
    (snap) => callback(snap.docs.map((d) => normalizeLegacyCard(d.id, d.data()))),
    (err) => {
      // eslint-disable-next-line no-console
      console.warn('[rakcha] listenToActionVeriteCards error:', err.message);
    }
  );
}

/** Add a new card to Firestore with complete backward & forward schema compatibility. */
export async function createCardInFirestore(
  cardData: Omit<GameCard, 'id' | 'createdAt'>,
  adminUid?: string
): Promise<GameCard> {
  const cardId = `card-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`;
  const docRef = doc(db, 'cards', cardId);
  const now = new Date().toISOString();

  const legacyCardType = cardData.category === 'shield'
    ? 'green'
    : cardData.category === 'special'
    ? 'gold'
    : cardData.category === 'action'
    ? 'red'
    : 'normal';

  const payload: Record<string, any> = {
    id: cardId,
    category: cardData.category,
    type: cardData.category,
    cardType: legacyCardType,
    title: cardData.title,
    name: cardData.title,
    content: cardData.content,
    questionOrAction: cardData.content,
    text: cardData.content,
    mode: cardData.mode || 'friends',
    difficulty: cardData.difficulty || 'medium',
    order: cardData.order ?? 0,
    description: cardData.description ? cardData.description : null,
    rule: cardData.description ? cardData.description : null,
    imageUrl: cardData.imageUrl ? cardData.imageUrl.trim() : null,
    specialOptions: cardData.specialOptions ? cardData.specialOptions : null,
    isActive: cardData.isActive,
    active: cardData.isActive,
    enabled: cardData.isActive,
    createdAt: now,
    updatedAt: now,
    createdBy: adminUid || 'admin',
    updatedBy: adminUid || 'admin',
  };

  await setDoc(docRef, payload);

  return {
    ...cardData,
    id: cardId,
    mode: cardData.mode || 'friends',
    difficulty: cardData.difficulty || 'medium',
    order: cardData.order ?? 0,
    createdAt: now,
    updatedAt: now,
    createdBy: adminUid || 'admin',
    updatedBy: adminUid || 'admin',
  };
}

/** Update an existing card in Firestore with merged sync across both schema versions. */
export async function updateCardInFirestore(
  id: string,
  updates: Partial<GameCard>,
  adminUid?: string
): Promise<void> {
  const docRef = doc(db, 'cards', id);
  const now = new Date().toISOString();

  const payload: Record<string, any> = {
    updatedAt: now,
    ...(adminUid ? { updatedBy: adminUid } : {}),
  };

  if (updates.category !== undefined) {
    payload.category = updates.category;
    payload.type = updates.category;
    payload.cardType = updates.category === 'shield'
      ? 'green'
      : updates.category === 'special'
      ? 'gold'
      : updates.category === 'action'
      ? 'red'
      : 'normal';
  }

  if (updates.title !== undefined) {
    payload.title = updates.title;
    payload.name = updates.title;
  }

  if (updates.content !== undefined) {
    payload.content = updates.content;
    payload.questionOrAction = updates.content;
    payload.text = updates.content;
  }

  if (updates.description !== undefined) {
    payload.description = updates.description ? updates.description : null;
    payload.rule = updates.description ? updates.description : null;
  }

  if (updates.imageUrl !== undefined) {
    payload.imageUrl = updates.imageUrl && updates.imageUrl.trim() ? updates.imageUrl.trim() : null;
  }

  if (updates.specialOptions !== undefined) {
    payload.specialOptions = updates.specialOptions ? updates.specialOptions : null;
  }

  if (updates.mode !== undefined) payload.mode = updates.mode;
  if (updates.difficulty !== undefined) payload.difficulty = updates.difficulty;
  if (updates.order !== undefined) payload.order = updates.order;

  if (updates.isActive !== undefined) {
    payload.isActive = updates.isActive;
    payload.active = updates.isActive;
    payload.enabled = updates.isActive;
  }

  await setDoc(docRef, payload, { merge: true });
}

/** Delete a card permanently from Firestore. */
export async function deleteCardInFirestore(id: string): Promise<void> {
  const docRef = doc(db, 'cards', id);
  await deleteDoc(docRef);
}

